import defaultTheme from 'tailwindcss/defaultTheme';

/** @type {import('tailwindcss').Config} */
export default {
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
        './resources/js/**/*.js',
        './resources/js/**/*.vue',
    ],
    darkMode: 'class',
    theme: {
        fontFamily: {
            satoshi: ['Satoshi', 'sans-serif'],
        },
        screens: {
            '2xsm': '375px',
            xsm: '425px',
            sm: '576px',
            md: '960px',
            lg: '1440px',
            xl: '1280px',
            '2xl': '1536px',
            '3xl': '2000px',
        },
        extend: {
            colors: {
                current: 'currentColor',
                transparent: 'transparent',
                white: '#FFFFFF',
                black: '#1C2434',
                red: '#FB5454',
                'black-2': '#010101',
                body: '#64748B',
                bodydark: '#AEB7C0',
                bodydark1: '#DEE4EE',
                bodydark2: '#8A99AF',
                primary: '#3C50E0',
                secondary: '#80CAEE',
                stroke: '#E2E8F0',
                gray: { ...defaultTheme.colors.gray, DEFAULT: '#EFF4FB' },
                graydark: '#333A48',
                'gray-2': '#F7F9FC',
                'gray-3': '#FAFAFA',
                whiten: '#F1F5F9',
                whiter: '#F5F7FD',
                'meta-1': '#DC3545',
                'meta-2': '#EFF2F7',
                'meta-3': '#10B981',
                success: '#219653',
                danger: '#D34053',
                warning: '#FFA70B',
            },
            fontSize: {
                'title-xl2': ['33px', '45px'],
                'title-lg': ['28px', '35px'],
                'title-md2': ['26px', '30px'],
                'title-md': ['24px', '30px'],
                'title-sm': ['20px', '26px'],
            },
            spacing: {
                4.5: '1.125rem',
                5.5: '1.375rem',
                6.5: '1.625rem',
                7.5: '1.875rem',
                12.5: '3.125rem',
                13: '3.25rem',
                15: '3.75rem',
                17.5: '4.375rem',
                26: '6.5rem',
                62.5: '15.625rem',
                72.5: '18.125rem',
            },
            zIndex: {
                999999: '999999',
                99999: '99999',
                9999: '9999',
                999: '999',
                99: '99',
            },
            boxShadow: {
                default: '0px 8px 13px -3px rgba(0, 0, 0, 0.07)',
                2: '0px 1px 4px rgba(0, 0, 0, 0.12)',
            },
            transitionProperty: { width: 'width', stroke: 'stroke' },
        },
    },
    plugins: [],
};
