<script setup>
import { computed, onMounted, ref, watch } from 'vue';
import { useRoute } from 'vue-router';
import api from '@/services/api';

const route=useRoute();const result=ref(null);const busy=ref(false);const error=ref('');const search=ref('');const expanded=ref(null);let timer;
const rows=computed(()=>result.value?.data||[]);
async function load(page=1){busy.value=true;error.value='';try{const response=await api.get('pages/audit',{params:{page,search:search.value||undefined}});result.value=response.data;}catch(e){error.value=e.response?.data?.message||'Գործողությունների պատմությունը չհաջողվեց բեռնել։';}finally{busy.value=false;}}
watch(search,()=>{clearTimeout(timer);timer=setTimeout(()=>load(1),250);});onMounted(()=>load());
function pretty(value){if(value===null||value===undefined||value==='')return 'Տվյալ չի գրանցվել';if(typeof value==='string'){try{return JSON.stringify(JSON.parse(value),null,2);}catch{return value;}}return JSON.stringify(value,null,2);}
</script>

<template>
  <div class="page-heading"><div><p class="eyebrow">ԱՆՓՈՓՈԽ ԳՈՐԾՈՂՈՒԹՅՈՒՆՆԵՐԻ ՄԱՏՅԱՆ</p><h1>{{ route.meta.title }}</h1><p class="muted">Դիտեք ով, երբ և ինչ փոփոխություն է կատարել։ Մատյանի գրառումները փոփոխման ենթակա չեն։</p></div></div>
  <div v-if="error" class="alert-error" role="alert">{{ error }}</div><section class="table-card"><div class="table-toolbar"><label class="search-input"><span class="search-icon"><AppIcon name="search" /></span><input v-model.trim="search" class="form-control" placeholder="Որոնել օգտատեր, գործողություն կամ բաժին"></label><span class="list-count">Գրառումներ՝ <b>{{ result?.pagination.total ?? '…' }}</b></span></div><div class="table-scroll"><table class="data-table audit-table"><thead><tr><th>Ամսաթիվ</th><th>Օգտատեր</th><th>Գործողություն</th><th>Բաժին / ID</th><th>Ցանցային հասցե</th><th>Մանրամասներ</th></tr></thead><tbody><template v-for="row in rows" :key="row.id"><tr><td>{{ row.created_at }}</td><td>{{ row.actor || 'Համակարգ' }}</td><td><strong>{{ row.action }}</strong></td><td>{{ row.entity }}<small class="cell-subtitle">{{ row.entity_id ?? '—' }}</small></td><td>{{ row.ip_address || '—' }}</td><td><button class="secondary-button compact-action" @click="expanded=expanded===row.id?null:row.id">{{ expanded===row.id?'Փակել':'Տեսնել փոփոխությունը' }}</button></td></tr><tr v-if="expanded===row.id" class="audit-detail-row"><td colspan="6"><div class="audit-detail-grid"><section><h3>Մինչև</h3><pre>{{ pretty(row.before_data) }}</pre></section><section><h3>Հետո</h3><pre>{{ pretty(row.after_data) }}</pre></section></div></td></tr></template><tr v-if="!busy&&result&&!rows.length"><td colspan="6" class="table-empty">{{ search?'Որոնմանը համապատասխան գրառում չկա։':'Գործողություններ դեռ գրանցված չեն։' }}</td></tr><tr v-if="busy&&!result"><td colspan="6" class="table-empty">Բեռնվում է…</td></tr></tbody></table></div><div v-if="result" class="pagination"><span>Ընդամենը՝ {{ result.pagination.total }} գրառում</span><div class="pagination-controls"><button :disabled="result.pagination.current_page<=1||busy" @click="load(result.pagination.current_page-1)">Նախորդ</button><span>Էջ {{ result.pagination.current_page }} / {{ result.pagination.last_page }}</span><button :disabled="result.pagination.current_page>=result.pagination.last_page||busy" @click="load(result.pagination.current_page+1)">Հաջորդ</button></div></div></section>
</template>
