<script setup>
import { computed,onMounted,reactive,ref,watch } from 'vue';import {useRoute} from 'vue-router';import api from '@/services/api';import{currentUser}from'@/router';
const route=useRoute(),user=ref(currentUser()),result=ref(null),options=ref({suppliers:[],products:[],orders:[]}),busy=ref(false),saving=ref(false),modal=ref(false),confirmOrder=ref(null),error=ref(''),notice=ref(''),search=ref('');let timer;
const page=computed(()=>route.path.slice(1)),isPurchases=computed(()=>page.value==='purchases'),rows=computed(()=>result.value?.data||[]),form=reactive({supplier_id:'',ordered_on:new Date().toISOString().slice(0,10),expected_on:'',note:'',items:[{product_id:'',qty:'',unit_cost:''}]}),receipt=reactive({purchase_order_id:'',received_on:new Date().toISOString().slice(0,10),invoice_no:'',contract_no:'',note:'',items:[]}),can=p=>Boolean(user.value?.permissions?.[p]);
async function load(pageNo=1){busy.value=true;error.value='';try{const r=await api.get(`pages/${page.value}`,{params:{page:pageNo,search:search.value||undefined}});result.value=r.data;}catch(e){error.value=e.response?.data?.message||'Ցանկը չհաջողվեց բեռնել։';}finally{busy.value=false;}}
watch(search,()=>{clearTimeout(timer);timer=setTimeout(()=>load(1),250);});onMounted(()=>{load();window.addEventListener('lager:user',e=>user.value=e.detail);});
async function openCreate(){error.value='';try{const r=await api.get(`purchasing/${page.value}/options`);options.value=r.data.data;if(isPurchases.value){Object.assign(form,{supplier_id:'',ordered_on:new Date().toISOString().slice(0,10),expected_on:'',note:'',items:[{product_id:'',qty:'',unit_cost:''}]});}else{Object.assign(receipt,{purchase_order_id:'',received_on:new Date().toISOString().slice(0,10),invoice_no:'',contract_no:'',note:'',items:[]});}modal.value=true;}catch(e){error.value=e.response?.data?.message||'Ձևի տվյալները չհաջողվեց բեռնել։';}}
function addItem(){form.items.push({product_id:'',qty:'',unit_cost:''});}function removeItem(i){if(form.items.length>1)form.items.splice(i,1);}
const order=computed(()=>options.value.orders.find(o=>Number(o.id)===Number(receipt.purchase_order_id))||null);
watch(()=>receipt.purchase_order_id,()=>{receipt.items=(order.value?.items||[]).map(i=>({purchase_order_item_id:i.id,name:i.name,code:i.code,unit:i.unit,expiry_control:i.expiry_control,ordered_qty:Number(i.ordered_qty),received_qty:Number(i.received_qty),remaining:Number(i.ordered_qty)-Number(i.received_qty),qty:'',lot_no:'',expires_on:'',bin_location:''}));});
async function save(){if(saving.value)return;saving.value=true;error.value='';try{if(isPurchases.value){const body={...form,supplier_id:Number(form.supplier_id),items:form.items.map(i=>({...i,product_id:Number(i.product_id),qty:Number(i.qty),unit_cost:Number(i.unit_cost)}))};await api.post('purchases',body);notice.value='Գնման պատվերն ուղարկվեց հաստատման։'}else{const body={...receipt,purchase_order_id:Number(receipt.purchase_order_id),items:receipt.items.filter(i=>Number(i.qty)>0).map(i=>({...i,qty:Number(i.qty)}))};await api.post('receipts',body);notice.value='Ապրանքի մուտքը գրանցվեց։'}modal.value=false;await load(1);setTimeout(()=>notice.value='',3200);}catch(e){error.value=Object.values(e.response?.data?.errors||{})[0]?.[0]||e.response?.data?.message||'Տվյալները չպահպանվեցին։';}finally{saving.value=false;}}
async function approve(){if(!confirmOrder.value)return;saving.value=true;error.value='';try{await api.post(`purchases/${confirmOrder.value.id}/approve`);confirmOrder.value=null;notice.value='Գնման պատվերը հաստատվեց։';await load(result.value?.pagination.current_page||1);setTimeout(()=>notice.value='',3200);}catch(e){error.value=e.response?.data?.message||'Պատվերը չհաստատվեց։';}finally{saving.value=false;}}
const status=s=>({pending:'Սպասում է հաստատման',approved:'Հաստատված',completed:'Ավարտված',cancelled:'Չեղարկված'}[s]||s);
</script>

<template><div class="page-heading"><div><p class="eyebrow">ԳՆՈՒՄ ԵՎ ՄՈՒՏՔԱԳՐՈՒՄ</p><h1>{{route.meta.title}}</h1><p class="muted">{{isPurchases?'Ստեղծեք մատակարարի պատվեր, ապա հաստատեք այն մինչև ապրանքի մուտքագրումը։':'Գրանցեք միայն հաստատված պատվերի փաստացի LOT-երն ու ստացված քանակները։'}}</p></div><button v-if="can(`${page}.create`)" class="primary-button" @click="openCreate"><span>＋</span>{{isPurchases?'Նոր գնման պատվեր':'Գրանցել մուտք'}}</button></div>
<div v-if="error&&!modal&&!confirmOrder" class="alert-error" role="alert">{{error}}</div><div v-if="notice" class="notice-success" role="status">{{notice}}</div>
<section class="table-card"><div class="table-toolbar"><label class="search-input"><span>⌕</span><input v-model="search" class="form-control" placeholder="Որոնել ըստ համարի, մատակարարի կամ հաշվի…"></label><div class="list-count">Ընդամենը՝ <b>{{result?.pagination.total??'…'}}</b></div></div><div class="table-scroll"><table class="data-table"><thead><tr><th v-for="(label,key) in result?.columns||{}" :key="key">{{label}}</th><th v-if="isPurchases">Գործողություն</th></tr></thead><tbody><tr v-for="row in rows" :key="row.id"><td v-for="(label,key) in result?.columns||{}" :key="key"><span v-if="key==='status'" class="workflow-status" :class="`state-${row[key]}`">{{status(row[key])}}</span><strong v-else-if="key.endsWith('_no')">{{row[key]}}</strong><span v-else>{{row[key]??'—'}}</span></td><td v-if="isPurchases"><button v-if="row.status==='pending'&&can('purchases.approve')" class="secondary-button compact-action" @click="confirmOrder=row">Հաստատել</button><span v-else class="muted">—</span></td></tr><tr v-if="!busy&&result&&!rows.length"><td :colspan="Object.keys(result.columns).length+(isPurchases?1:0)" class="table-empty">Գրառումներ դեռ չկան։</td></tr><tr v-if="busy&&!result"><td colspan="8" class="table-empty">Բեռնվում է…</td></tr></tbody></table></div><div v-if="result" class="pagination"><span>Ընդամենը՝ {{result.pagination.total}} գրառում</span><div class="pagination-controls"><button :disabled="result.pagination.current_page<=1||busy" @click="load(result.pagination.current_page-1)">← Նախորդ</button><span>Էջ {{result.pagination.current_page}} / {{result.pagination.last_page}}</span><button :disabled="result.pagination.current_page>=result.pagination.last_page||busy" @click="load(result.pagination.current_page+1)">Հաջորդ →</button></div></div></section>

<div v-if="modal" class="modal-backdrop" @click.self="modal=false"><form class="modal-card purchase-modal" @submit.prevent="save"><div class="modal-header"><div><p class="eyebrow">{{isPurchases?'ՄԱՏԱԿԱՐԱՐԻ ՊԱՏՎԵՐ':'ԱՊՐԱՆՔԻ ՄՈՒՏՔ'}}</p><h2>{{isPurchases?'Նոր գնման պատվեր':'Գրանցել ապրանքի մուտք'}}</h2><p>{{isPurchases?'Պատվերը կհայտնվի հաստատման հերթում։':'Ընդունվող քանակը չի կարող գերազանցել պատվերի չստացված մնացորդը։'}}</p></div><button class="icon-button close-button" type="button" @click="modal=false">×</button></div>
<template v-if="isPurchases"><div class="form-grid"><label class="form-field">Մատակարար *<select v-model="form.supplier_id" class="form-control" required><option value="">Ընտրել մատակարարին</option><option v-for="s in options.suppliers" :key="s.id" :value="s.id">{{s.name}}</option></select></label><label class="form-field">Պատվերի ամսաթիվ *<input v-model="form.ordered_on" class="form-control" type="date" required></label><label class="form-field">Սպասվող մուտք<input v-model="form.expected_on" class="form-control" type="date" :min="form.ordered_on"></label><label class="form-field">Նշում<input v-model.trim="form.note" class="form-control"></label></div><div class="transfer-lines"><div class="section-label">Պատվերի ապրանքներ</div><div v-for="(line,i) in form.items" :key="i" class="purchase-line"><label class="form-field">Ապրանք<select v-model="line.product_id" class="form-control" required><option value="">Ընտրել</option><option v-for="p in options.products" :key="p.id" :value="p.id">{{p.code}} · {{p.name}}</option></select></label><label class="form-field">Քանակ<input v-model="line.qty" class="form-control" type="number" min="0.001" step="0.001" required></label><label class="form-field">Միավորի գին<input v-model="line.unit_cost" class="form-control" type="number" min="0" step="0.01" required></label><button v-if="form.items.length>1" class="icon-button danger remove-line" type="button" @click="removeItem(i)">×</button></div><button class="secondary-button add-line" type="button" @click="addItem">＋ Ավելացնել ապրանք</button></div></template>
<template v-else><div class="form-grid"><label class="form-field span-2">Հաստատված պատվեր *<select v-model="receipt.purchase_order_id" class="form-control" required><option value="">Ընտրել պատվերը</option><option v-for="o in options.orders" :key="o.id" :value="o.id">{{o.order_no}} · {{o.supplier}}</option></select></label><label class="form-field">Ստացման ամսաթիվ *<input v-model="receipt.received_on" class="form-control" type="date" required></label><label class="form-field">Հաշիվ-ապրանքագիր<input v-model.trim="receipt.invoice_no" class="form-control"></label><label class="form-field">Պայմանագիր<input v-model.trim="receipt.contract_no" class="form-control"></label><label class="form-field">Նշում<input v-model.trim="receipt.note" class="form-control"></label></div><div v-if="receipt.items.length" class="receipt-lines"><div class="section-label">Փաստացի ընդունում</div><div v-for="line in receipt.items" :key="line.purchase_order_item_id" class="receipt-line"><div><b>{{line.code}} · {{line.name}}</b><small class="cell-subtitle">Պատվեր՝ {{line.ordered_qty}} · Մուտքագրված՝ {{line.received_qty}} · Մնացորդ՝ {{line.remaining}} {{line.unit}}</small></div><label class="form-field">Քանակ<input v-model="line.qty" class="form-control" type="number" min="0" :max="line.remaining" step="0.001"></label><label class="form-field">LOT համար<input v-model.trim="line.lot_no" class="form-control" :required="Number(line.qty)>0"></label><label class="form-field">Պիտանի է մինչև<input v-model="line.expires_on" class="form-control" type="date" :min="receipt.received_on" :required="Number(line.qty)>0&&line.expiry_control"></label><label class="form-field">Դարակ<input v-model.trim="line.bin_location" class="form-control"></label></div></div></template>
<p v-if="error" class="form-error">{{error}}</p><div class="modal-actions"><button type="button" class="secondary-button" @click="modal=false">Չեղարկել</button><button class="primary-button" :disabled="saving">{{saving?'Պահպանվում է…':'Պահպանել'}}</button></div></form></div>
<div v-if="confirmOrder" class="modal-backdrop" @click.self="confirmOrder=null"><section class="modal-card confirm-card"><div class="metric-icon blue">✓</div><h2>Հաստատե՞լ գնման պատվերը</h2><p><b>{{confirmOrder.order_no}}</b> · {{confirmOrder.supplier}}</p><p class="muted">Հաստատումից հետո պատվերի հիման վրա կարելի կլինի գրանցել ապրանքի մուտքը։</p><p v-if="error" class="form-error">{{error}}</p><div class="modal-actions"><button class="secondary-button" @click="confirmOrder=null">Չեղարկել</button><button class="primary-button" :disabled="saving" @click="approve">Հաստատել պատվերը</button></div></section></div></template>
