<script setup>
import Pagination from '@/components/Pagination.vue';
import{computed,onMounted,reactive,ref,watch}from'vue';import{useRoute}from'vue-router';import api from'@/services/api';import{currentUser}from'@/router';import { formatDisplayDate } from '@/dateUtils';import ExportActions from '@/components/ExportActions.vue';
const route=useRoute(),user=ref(currentUser()),result=ref(null),options=ref({products:[],branches:[]}),lots=ref([]),busy=ref(false),saving=ref(false),modal=ref(''),error=ref(''),notice=ref(''),search=ref('');let timer;
const rows=computed(()=>result.value?.data||[]),can=p=>Boolean(user.value?.permissions?.[p]),location=computed(()=>Number(user.value?.location_id||0));
const consume=reactive({product_id:'',qty:'',location_id:0,issue_type:'usage',reason_note:''});
const adjust=reactive({product_id:'',location_id:0,lot_id:'',delta_qty:'',reason:'',lot_no:'',expires_on:'',unit_cost:'',bin_location:''});
async function load(page=1,pageSize=result.value?.pagination.per_page||25){busy.value=true;error.value='';try{const r=await api.get('pages/stock',{params:{page,per_page:pageSize,search:search.value||undefined}});result.value=r.data;}catch(e){error.value=e.response?.data?.message||'Մնացորդը չհաջողվեց բեռնել։';}finally{busy.value=false;}}
watch(search,()=>{clearTimeout(timer);timer=setTimeout(()=>load(1),250);});onMounted(()=>{load();window.addEventListener('lager:user',e=>user.value=e.detail);});
async function open(kind,row=null){error.value='';try{const r=await api.get('catalog/stock/options');options.value=r.data.data;const initial=location.value;modal.value=kind;if(kind==='consume')Object.assign(consume,{product_id:row?.id||'',qty:'',location_id:initial,issue_type:'usage',reason_note:''});else{Object.assign(adjust,{product_id:row?.id||'',location_id:initial,lot_id:'',delta_qty:'',reason:'',lot_no:'',expires_on:'',unit_cost:'',bin_location:''});await loadLots();}}catch(e){error.value=e.response?.data?.message||'Ձևը չհաջողվեց բացել։';}}
async function loadLots(){lots.value=[];if(!adjust.product_id)return;try{const r=await api.get('stock/lots',{params:{product_id:adjust.product_id,location_id:adjust.location_id}});lots.value=r.data.data;}catch(e){error.value=e.response?.data?.message||'LOT-երը չհաջողվեց բեռնել։';}}
watch(()=>[adjust.product_id,adjust.location_id],loadLots);
const isNewLot=computed(()=>!adjust.lot_id&&Number(adjust.delta_qty)>0);
async function save(){if(saving.value)return;saving.value=true;error.value='';const mode=modal.value;try{if(mode==='consume')await api.post('stock/consume',{...consume,product_id:Number(consume.product_id),qty:Number(consume.qty),location_id:Number(consume.location_id)});else await api.post('stock/adjust',{...adjust,product_id:Number(adjust.product_id),lot_id:adjust.lot_id?Number(adjust.lot_id):null,delta_qty:Number(adjust.delta_qty),location_id:Number(adjust.location_id),unit_cost:adjust.unit_cost===''?undefined:Number(adjust.unit_cost)});modal.value='';notice.value=mode==='consume'?'Ելքը գրանցվեց։':'Պաշարի ուղղումը գրանցվեց։';await load(result.value?.pagination.current_page||1);setTimeout(()=>notice.value='',3200);}catch(e){error.value=Object.values(e.response?.data?.errors||{})[0]?.[0]||e.response?.data?.message||'Գործողությունը չպահպանվեց։';}finally{saving.value=false;}}
const locationOptions=computed(()=>options.value.branches||[]);const currentProduct=computed(()=>options.value.products.find(p=>Number(p.id)===Number(adjust.product_id)));
</script>

<template><div class="page-heading"><div><p class="eyebrow">ՊԱՇԱՐԻ ՎԵՐԱՀՍԿՈՒՄ</p><h1>{{route.meta.title}}</h1><p class="muted">Մնացորդը հաշվարկվում է LOT-երով․ ելքը բաշխվում է ժամկետների FEFO հերթականությամբ։</p></div><div class="stock-actions"><RouterLink class="secondary-button" to="/stock/matrix"><AppIcon name="chart" />Մնացորդների մատրիցա</RouterLink><button v-if="can('stock.edit')" class="secondary-button" @click="open('adjust')"><AppIcon name="adjust" />Ճշգրտել մնացորդը</button><button v-if="can('stock.create')" class="primary-button" @click="open('consume')"><AppIcon name="arrowDown" />Գրանցել ելք</button></div></div>
<div v-if="error&&!modal" class="alert-error" role="alert">{{error}}</div><div v-if="notice" class="notice-success" role="status">{{notice}}</div>
<section class="table-card"><div class="table-toolbar"><label class="search-input"><span class="search-icon"><AppIcon name="search" /></span><input v-model="search" class="form-control" placeholder="Որոնել կոդով կամ ապրանքով…"></label><div class="list-count">Ընդամենը՝ <b>{{result?.pagination.total??'…'}}</b> ապրանք</div><ExportActions page="stock" :search="search" :disabled="busy" /></div><div class="table-scroll"><table class="data-table"><thead><tr><th>Կոդ</th><th>Ապրանք</th><th>Մնացորդ</th><th>Միավոր</th><th>Նվազագույն</th><th v-if="can('purchases.view')">Գնահատված արժեք</th><th>Գործողություն</th></tr></thead><tbody><tr v-for="row in rows" :key="row.id"><td><span class="code-pill">{{row.code}}</span></td><td><strong>{{row.name}}</strong></td><td><b>{{Number(row.quantity).toLocaleString('hy-AM',{maximumFractionDigits:3})}}</b></td><td>{{row.unit}}</td><td>{{row.min_qty}}</td><td v-if="can('purchases.view')">{{Number(row.stock_value).toLocaleString('hy-AM',{maximumFractionDigits:2})}} ֏</td><td><div class="table-actions"><button v-if="can('stock.create')" class="icon-button" type="button" aria-label="Գրանցել ելք" title="Գրանցել ելք" @click="open('consume',row)"><AppIcon name="trendDown" /></button><button v-if="can('stock.edit')" class="icon-button" type="button" aria-label="Ճշգրտել" title="Ճշգրտել" @click="open('adjust',row)"><AppIcon name="adjust" /></button></div></td></tr><tr v-if="!busy&&result&&!rows.length"><td :colspan="can('purchases.view') ? 7 : 6" class="table-empty">{{search?'Որոնմանը համապատասխան ապրանք չկա։':'Մնացորդ չկա։'}}</td></tr><tr v-if="busy&&!result"><td :colspan="can('purchases.view') ? 7 : 6" class="table-empty">Բեռնվում է…</td></tr></tbody></table></div><Pagination v-if="result" :pagination="result.pagination" :busy="busy" @page-change="load" @per-page-change="load(1, $event)" /></section>
<div v-if="modal" class="modal-backdrop" @click.self="modal=''" @keydown.esc="modal=''"><form class="modal-card stock-modal" @submit.prevent="save"><div class="modal-header"><div><p class="eyebrow">{{modal==='consume'?'ՊԱՇԱՐԻ ԵԼՔ':'ՊԱՇԱՐԻ ՈՒՂՂՈՒՄ'}}</p><h2>{{modal==='consume'?'Գրանցել ներքին ելք':'Ճշգրտել մնացորդը'}}</h2><p>{{modal==='consume'?'LOT-երը կհանվեն ըստ ժամկետի՝ FEFO հերթականությամբ։':'Յուրաքանչյուր ճշգրտում գրանցվում է շարժերի մատյանում։'}}</p></div><button class="icon-button close-button" type="button" @click="modal=''"><AppIcon name="xmark" /></button></div>
<div v-if="modal==='consume'" class="form-grid"><label class="form-field span-2">Ապրանք *<select v-searchable-select v-model="consume.product_id" class="form-control" required><option value="">Ընտրել</option><option v-for="p in options.products" :key="p.id" :value="p.id">{{p.code}} · {{p.name}}</option></select></label><label class="form-field">Ելքի քանակ *<input v-model="consume.qty" class="form-control" type="number" min="0.001" step="0.001" required></label><label class="form-field">Պահեստ<select v-searchable-select v-model="consume.location_id" class="form-control" :disabled="location>0"><option :value="0">Կենտրոնական պահեստ</option><option v-for="b in locationOptions.filter(x=>x.code!=='CENTRAL')" :key="b.id" :value="b.id">{{b.name}}</option></select></label><label class="form-field span-2">Ելքի պատճառ<select v-searchable-select v-model="consume.issue_type" class="form-control"><option value="usage">Ներքին օգտագործում</option><option value="expired">Ժամկետանցի դուրսգրում</option><option value="damaged">Վնասված ապրանք</option><option value="other">Այլ պատճառ</option></select></label><label v-if="consume.issue_type==='other'" class="form-field span-2">Բացատրություն *<textarea v-model.trim="consume.reason_note" class="form-control" required></textarea></label></div>
<div v-else class="form-grid"><label class="form-field">Ապրանք *<select v-searchable-select v-model="adjust.product_id" class="form-control" required><option value="">Ընտրել</option><option v-for="p in options.products" :key="p.id" :value="p.id">{{p.code}} · {{p.name}}</option></select></label><label class="form-field">Պահեստ<select v-searchable-select v-model="adjust.location_id" class="form-control" :disabled="location>0"><option :value="0">Կենտրոնական պահեստ</option><option v-for="b in locationOptions.filter(x=>x.code!=='CENTRAL')" :key="b.id" :value="b.id">{{b.name}}</option></select></label><label class="form-field span-2">Գոյություն ունեցող LOT<select v-searchable-select v-model="adjust.lot_id" class="form-control"><option value="">Նոր դրական մնացորդ</option><option v-for="lot in lots" :key="lot.id" :value="lot.id">{{lot.lot_no}} · {{lot.expires_on ? formatDisplayDate(lot.expires_on) : 'Առանց ժամկետի'}} · {{lot.qty}} միավոր</option></select></label><label class="form-field">Քանակի փոփոխություն *<input v-model="adjust.delta_qty" class="form-control" type="number" step="0.001" required placeholder="Դրական՝ ավելացնել, բացասական՝ նվազեցնել"></label><label class="form-field">Պատճառ *<input v-model.trim="adjust.reason" class="form-control" minlength="3" required></label><template v-if="isNewLot"><label class="form-field">Նոր LOT համար *<input v-model.trim="adjust.lot_no" class="form-control" required></label><label class="form-field">Պիտանի է մինչև<DatePicker v-model="adjust.expires_on" :required="currentProduct?.expiry_control" /></label><label v-if="can('purchases.view')" class="form-field">Միավորի արժեք<input v-model="adjust.unit_cost" class="form-control" type="number" min="0" step="0.01" :placeholder="String(currentProduct?.purchase_price||0)"></label><label class="form-field">Պահեստային տեղ<input v-model.trim="adjust.bin_location" class="form-control"></label></template></div><p v-if="error" class="form-error">{{error}}</p><div class="modal-actions"><button type="button" class="secondary-button" @click="modal=''">Չեղարկել</button><button class="primary-button" :disabled="saving">{{saving?'Պահպանվում է…':'Պահպանել շարժը'}}</button></div></form></div></template>
