<?php
$dispatchId=(int)($_GET['id']??0);
$dispatchSql='SELECT r.*,b.name branch_name,requester.name requester_name,sender.name sender_name,receiver.name receiver_name FROM stock_requests r JOIN branches b ON b.id=r.branch_id JOIN users requester ON requester.id=r.requested_by LEFT JOIN users sender ON sender.id=r.sent_by LEFT JOIN users receiver ON receiver.id=r.received_by WHERE r.id=? AND r.status IN (\'shipped\',\'received\',\'closed\')'.(currentLocation()?' AND r.branch_id='.currentLocation():'').' LIMIT 1';
$dispatchQuery=db()->prepare($dispatchSql);
$dispatchQuery->execute([$dispatchId]);
$dispatch=$dispatchQuery->fetch();
if(!$dispatch){http_response_code(404);exit('Բաշխման փաստաթուղթը չի գտնվել։');}
$itemQuery=db()->prepare('SELECT i.requested_qty,i.approved_qty,p.code,p.name,p.unit FROM request_items i JOIN products p ON p.id=i.product_id WHERE i.request_id=? ORDER BY i.id');
$itemQuery->execute([$dispatchId]);
$dispatchItems=$itemQuery->fetchAll();
?>
<!doctype html>
<html lang="hy"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Բաշխման փաստաթուղթ · <?=h($dispatch['request_no'])?></title>
<style>
*{box-sizing:border-box}body{margin:0;padding:28px;background:#eef2f8;color:#17243a;font:14px/1.5 "Segoe UI",Arial,sans-serif}.paper{max-width:920px;margin:0 auto;padding:40px;border:1px solid #e1e7f0;border-radius:12px;background:#fff;box-shadow:0 12px 32px #16233a12}.toolbar{display:flex;justify-content:flex-end;gap:10px;max-width:920px;margin:0 auto 14px}.button{border:1px solid #d8e0ed;border-radius:8px;padding:10px 14px;background:#fff;color:#24334d;font:inherit;text-decoration:none;cursor:pointer}.button.primary{border-color:#485cf5;background:#485cf5;color:#fff}.eyebrow{margin:0 0 6px;color:#5266ea;font-size:11px;font-weight:800;letter-spacing:.13em;text-transform:uppercase}h1{margin:0;font-size:26px;letter-spacing:-.03em}.sub{margin:6px 0 22px;color:#75839a}.meta{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px;margin:22px 0;padding:18px;border:1px solid #e5eaf2;border-radius:10px;background:#f8faff}.meta div{display:grid;gap:3px}.meta small{color:#76849a}.meta b{overflow-wrap:anywhere}.reason{margin:18px 0;padding:12px 14px;border-left:3px solid #5266ea;background:#f6f8ff}.reason small{display:block;color:#76849a}.items{width:100%;border-collapse:collapse;margin:18px 0}.items th,.items td{padding:11px 10px;border-bottom:1px solid #e8edf4;text-align:left}.items th{color:#5e6d84;background:#f6f8fc;font-size:11px}.items td.num{text-align:right;font-variant-numeric:tabular-nums}.signatures{display:grid;grid-template-columns:1fr 1fr;gap:32px;margin-top:42px}.signatures div{padding-top:9px;border-top:1px solid #aeb9c9;color:#67768d}.print-note{margin-top:24px;color:#8793a6;font-size:11px}@media(max-width:640px){body{padding:12px}.paper{padding:20px}.meta{grid-template-columns:1fr 1fr}h1{font-size:21px}}@media print{@page{size:A4;margin:14mm}body{padding:0;background:#fff}.paper{max-width:none;margin:0;padding:0;border:0;border-radius:0;box-shadow:none}.toolbar,.print-note{display:none}.meta{break-inside:avoid}}
</style></head><body>
<div class="toolbar"><a class="button" href="?page=requests">Վերադառնալ պահանջագրերին</a><button class="button primary" type="button" onclick="window.print()">Տպել / պահպանել PDF</button></div>
<main class="paper"><p class="eyebrow">Դիագեն Պլյուս · Բաշխման փաստաթուղթ</p><h1><?=h($dispatch['request_no'])?></h1><p class="sub">Մասնաճյուղին ուղարկված ապրանքների և ստացման հաստատման ակտ</p>
<section class="meta"><div><small>Մասնաճյուղ</small><b><?=h($dispatch['branch_name'])?></b></div><div><small>Պահանջող աշխատակից</small><b><?=h($dispatch['requester_name'])?></b></div><div><small>Կարգավիճակ</small><b><?=h(['shipped'=>'Ուղարկված','received'=>'Ստացված','closed'=>'Փակված'][$dispatch['status']]??$dispatch['status'])?></b></div><div><small>Պահանջի ամսաթիվ</small><b><?=h(date('d.m.Y H:i',strtotime($dispatch['created_at'])))?></b></div><div><small>Ուղարկող</small><b><?=h($dispatch['sender_name']??'—')?></b></div><div><small>Ուղարկման ամսաթիվ</small><b><?=h($dispatch['sent_at']?date('d.m.Y H:i',strtotime($dispatch['sent_at'])):'—')?></b></div><div><small>Ստացող</small><b><?=h($dispatch['receiver_name']??'—')?></b></div><div><small>Ստացման ամսաթիվ</small><b><?=h($dispatch['received_at']?date('d.m.Y H:i',strtotime($dispatch['received_at'])):'—')?></b></div><div><small>Հրատապություն</small><b><?=h(['urgent'=>'Շտապ','high'=>'Բարձր','normal'=>'Սովորական'][$dispatch['urgency']]??$dispatch['urgency'])?></b></div></section>
<?php if(trim((string)$dispatch['reason'])!==''):?><p class="reason"><small>Պահանջի հիմնավորում</small><?=h($dispatch['reason'])?></p><?php endif?>
<table class="items"><thead><tr><th>Կոդ</th><th>Ապրանք</th><th>Պահանջված</th><th>Ուղարկված</th><th>Միավոր</th></tr></thead><tbody><?php foreach($dispatchItems as $dispatchItem):?><tr><td><?=h($dispatchItem['code'])?></td><td><?=h($dispatchItem['name'])?></td><td class="num"><?=num($dispatchItem['requested_qty'])?></td><td class="num"><b><?=num($dispatchItem['approved_qty'])?></b></td><td><?=h($dispatchItem['unit'])?></td></tr><?php endforeach?></tbody></table>
<div class="signatures"><div>Ուղարկող՝ <?=h($dispatch['sender_name']??'________________')?></div><div>Ստացող՝ <?=h($dispatch['receiver_name']??'________________')?></div></div><p class="print-note">Ընտրեք «Տպել / պահպանել PDF»՝ բաշխման փաստաթուղթը տպելու կամ PDF պահպանելու համար։</p></main></body></html>
