SET NAMES utf8mb4;
CREATE TABLE IF NOT EXISTS roles (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(80) NOT NULL UNIQUE, title VARCHAR(120) NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS permissions (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, code VARCHAR(100) NOT NULL UNIQUE, title VARCHAR(140) NOT NULL, module VARCHAR(80) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS role_permissions (
 role_id BIGINT UNSIGNED NOT NULL, permission_id BIGINT UNSIGNED NOT NULL, PRIMARY KEY(role_id,permission_id), FOREIGN KEY(role_id) REFERENCES roles(id) ON DELETE CASCADE, FOREIGN KEY(permission_id) REFERENCES permissions(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS users (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(160) NOT NULL, email VARCHAR(190) NOT NULL UNIQUE, password VARCHAR(255) NOT NULL, role_id BIGINT UNSIGNED NOT NULL, branch_id BIGINT UNSIGNED NULL, active TINYINT(1) NOT NULL DEFAULT 1, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(role_id) REFERENCES roles(id), INDEX(branch_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS branches (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(160) NOT NULL, code VARCHAR(40) NOT NULL UNIQUE, address VARCHAR(255) NULL, manager VARCHAR(160) NULL, phone VARCHAR(50) NULL, active TINYINT(1) NOT NULL DEFAULT 1, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS suppliers (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(190) NOT NULL, tax_id VARCHAR(50) NULL, address VARCHAR(255) NULL, contact_name VARCHAR(160) NULL, phone VARCHAR(50) NULL, email VARCHAR(190) NULL, bank_details VARCHAR(255) NULL, contract_no VARCHAR(100) NULL, contract_start DATE NULL, contract_end DATE NULL, payment_terms VARCHAR(190) NULL, delivery_days INT NULL, active TINYINT(1) NOT NULL DEFAULT 1, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS categories (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(120) NOT NULL UNIQUE, parent_id BIGINT UNSIGNED NULL, FOREIGN KEY(parent_id) REFERENCES categories(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS products (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, code VARCHAR(80) NOT NULL UNIQUE, barcode VARCHAR(100) NULL, name VARCHAR(190) NOT NULL, category_id BIGINT UNSIGNED NULL, subcategory VARCHAR(120) NULL, supplier_id BIGINT UNSIGNED NULL, purchase_price DECIMAL(14,2) NOT NULL DEFAULT 0, manufacturer VARCHAR(160) NULL, unit VARCHAR(50) NOT NULL DEFAULT 'հատ', package VARCHAR(120) NULL, min_qty DECIMAL(12,3) NOT NULL DEFAULT 0, optimal_qty DECIMAL(12,3) NOT NULL DEFAULT 0, max_qty DECIMAL(12,3) NOT NULL DEFAULT 0, storage_conditions VARCHAR(190) NULL, refrigerated TINYINT(1) NOT NULL DEFAULT 0, lot_control TINYINT(1) NOT NULL DEFAULT 1, expiry_control TINYINT(1) NOT NULL DEFAULT 1, active TINYINT(1) NOT NULL DEFAULT 1, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, CONSTRAINT uq_products_barcode UNIQUE(barcode), FOREIGN KEY(category_id) REFERENCES categories(id) ON DELETE SET NULL, CONSTRAINT fk_products_supplier FOREIGN KEY(supplier_id) REFERENCES suppliers(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS stock_lots (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, product_id BIGINT UNSIGNED NOT NULL, purchase_order_id BIGINT UNSIGNED NULL, location_id BIGINT UNSIGNED NOT NULL DEFAULT 0, lot_no VARCHAR(100) NOT NULL, expires_on DATE NULL, received_on DATE NOT NULL, supplier_id BIGINT UNSIGNED NULL, unit_cost DECIMAL(14,2) NOT NULL DEFAULT 0, bin_location VARCHAR(100) NULL, qty DECIMAL(12,3) NOT NULL DEFAULT 0, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(product_id) REFERENCES products(id), FOREIGN KEY(supplier_id) REFERENCES suppliers(id) ON DELETE SET NULL, INDEX(location_id,product_id,expires_on)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS stock_requests (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, request_no VARCHAR(40) NOT NULL UNIQUE, branch_id BIGINT UNSIGNED NOT NULL, requested_by BIGINT UNSIGNED NOT NULL, status VARCHAR(40) NOT NULL DEFAULT 'draft', urgency VARCHAR(30) NOT NULL DEFAULT 'normal', reason TEXT NULL, rejection_reason TEXT NULL, reviewed_by BIGINT UNSIGNED NULL, sent_by BIGINT UNSIGNED NULL, received_by BIGINT UNSIGNED NULL, sent_at DATETIME NULL, received_at DATETIME NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(branch_id) REFERENCES branches(id), FOREIGN KEY(requested_by) REFERENCES users(id), FOREIGN KEY(sent_by) REFERENCES users(id) ON DELETE SET NULL, FOREIGN KEY(received_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS request_items (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, request_id BIGINT UNSIGNED NOT NULL, product_id BIGINT UNSIGNED NOT NULL, requested_qty DECIMAL(12,3) NOT NULL, approved_qty DECIMAL(12,3) NOT NULL DEFAULT 0, note VARCHAR(255) NULL, FOREIGN KEY(request_id) REFERENCES stock_requests(id) ON DELETE CASCADE, FOREIGN KEY(product_id) REFERENCES products(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS purchase_orders (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, order_no VARCHAR(40) NOT NULL UNIQUE, supplier_id BIGINT UNSIGNED NOT NULL, status VARCHAR(30) NOT NULL DEFAULT 'pending', ordered_on DATE NOT NULL, expected_on DATE NULL, created_by BIGINT UNSIGNED NOT NULL, approved_by BIGINT UNSIGNED NULL, approved_at DATETIME NULL, note TEXT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(supplier_id) REFERENCES suppliers(id), FOREIGN KEY(created_by) REFERENCES users(id), FOREIGN KEY(approved_by) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS purchase_order_items (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, purchase_order_id BIGINT UNSIGNED NOT NULL, product_id BIGINT UNSIGNED NOT NULL, ordered_qty DECIMAL(12,3) NOT NULL, received_qty DECIMAL(12,3) NOT NULL DEFAULT 0, unit_cost DECIMAL(14,2) NOT NULL, FOREIGN KEY(purchase_order_id) REFERENCES purchase_orders(id) ON DELETE CASCADE, FOREIGN KEY(product_id) REFERENCES products(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS receipts (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, receipt_no VARCHAR(40) NOT NULL UNIQUE, purchase_order_id BIGINT UNSIGNED NULL, supplier_id BIGINT UNSIGNED NOT NULL, invoice_no VARCHAR(100) NULL, contract_no VARCHAR(100) NULL, received_by BIGINT UNSIGNED NOT NULL, received_on DATE NOT NULL, note TEXT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(purchase_order_id) REFERENCES purchase_orders(id), FOREIGN KEY(supplier_id) REFERENCES suppliers(id), FOREIGN KEY(received_by) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS receipt_items (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, receipt_id BIGINT UNSIGNED NOT NULL, purchase_order_item_id BIGINT UNSIGNED NULL, product_id BIGINT UNSIGNED NOT NULL, lot_id BIGINT UNSIGNED NULL, qty DECIMAL(12,3) NOT NULL, unit_cost DECIMAL(14,2) NOT NULL DEFAULT 0, FOREIGN KEY(receipt_id) REFERENCES receipts(id) ON DELETE CASCADE, FOREIGN KEY(purchase_order_item_id) REFERENCES purchase_order_items(id) ON DELETE SET NULL, FOREIGN KEY(product_id) REFERENCES products(id), FOREIGN KEY(lot_id) REFERENCES stock_lots(id), INDEX(receipt_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS movements (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, movement_no VARCHAR(40) NOT NULL, type VARCHAR(40) NOT NULL, product_id BIGINT UNSIGNED NOT NULL, lot_id BIGINT UNSIGNED NULL, from_location BIGINT UNSIGNED NULL, to_location BIGINT UNSIGNED NULL, qty DECIMAL(12,3) NOT NULL, unit_cost DECIMAL(14,2) NOT NULL DEFAULT 0, reference VARCHAR(100) NULL, reason TEXT NULL, actor_id BIGINT UNSIGNED NOT NULL, happened_at DATETIME NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(product_id) REFERENCES products(id), FOREIGN KEY(lot_id) REFERENCES stock_lots(id), FOREIGN KEY(actor_id) REFERENCES users(id), INDEX(happened_at,type,product_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS inventory_sessions (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, inventory_no VARCHAR(40) NOT NULL UNIQUE, location_id BIGINT UNSIGNED NOT NULL, status VARCHAR(30) NOT NULL DEFAULT 'open', started_by BIGINT UNSIGNED NOT NULL, approved_by BIGINT UNSIGNED NULL, started_at DATETIME NOT NULL, closed_at DATETIME NULL, note TEXT NULL, FOREIGN KEY(started_by) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS inventory_lines (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, session_id BIGINT UNSIGNED NOT NULL, product_id BIGINT UNSIGNED NOT NULL, lot_id BIGINT UNSIGNED NULL, expected_qty DECIMAL(12,3) NOT NULL, counted_qty DECIMAL(12,3) NULL, difference_reason VARCHAR(255) NULL, counted_lot_no VARCHAR(100) NULL, counted_expires_on DATE NULL, counted_supplier_id BIGINT UNSIGNED NULL, counted_bin_location VARCHAR(100) NULL, counted_unit_cost DECIMAL(14,2) NULL, FOREIGN KEY(session_id) REFERENCES inventory_sessions(id) ON DELETE CASCADE, FOREIGN KEY(product_id) REFERENCES products(id), FOREIGN KEY(lot_id) REFERENCES stock_lots(id), CONSTRAINT fk_inventory_lines_counted_supplier FOREIGN KEY(counted_supplier_id) REFERENCES suppliers(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS transfers (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, transfer_no VARCHAR(40) NOT NULL UNIQUE, from_branch BIGINT UNSIGNED NOT NULL, to_branch BIGINT UNSIGNED NOT NULL, product_id BIGINT UNSIGNED NOT NULL, lot_id BIGINT UNSIGNED NULL, qty DECIMAL(12,3) NOT NULL, status VARCHAR(30) NOT NULL DEFAULT 'pending', requested_by BIGINT UNSIGNED NOT NULL, approved_by BIGINT UNSIGNED NULL, shipped_by BIGINT UNSIGNED NULL, received_by BIGINT UNSIGNED NULL, reason TEXT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, accepted_at DATETIME NULL, FOREIGN KEY(from_branch) REFERENCES branches(id), FOREIGN KEY(to_branch) REFERENCES branches(id), FOREIGN KEY(product_id) REFERENCES products(id), FOREIGN KEY(lot_id) REFERENCES stock_lots(id), FOREIGN KEY(shipped_by) REFERENCES users(id) ON DELETE SET NULL, FOREIGN KEY(received_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS transfer_items (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, transfer_id BIGINT UNSIGNED NOT NULL, product_id BIGINT UNSIGNED NOT NULL, qty DECIMAL(12,3) NOT NULL, FOREIGN KEY(transfer_id) REFERENCES transfers(id) ON DELETE CASCADE, FOREIGN KEY(product_id) REFERENCES products(id), INDEX(transfer_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS returns (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, return_no VARCHAR(40) NOT NULL, direction VARCHAR(40) NOT NULL, from_location BIGINT UNSIGNED NOT NULL DEFAULT 0, supplier_id BIGINT UNSIGNED NULL, product_id BIGINT UNSIGNED NOT NULL, lot_id BIGINT UNSIGNED NULL, qty DECIMAL(12,3) NOT NULL, reason TEXT NOT NULL, status VARCHAR(30) NOT NULL DEFAULT 'posted', actor_id BIGINT UNSIGNED NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(supplier_id) REFERENCES suppliers(id), FOREIGN KEY(product_id) REFERENCES products(id), FOREIGN KEY(lot_id) REFERENCES stock_lots(id), FOREIGN KEY(actor_id) REFERENCES users(id), INDEX(return_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS audit_logs (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, actor_id BIGINT UNSIGNED NULL, action VARCHAR(100) NOT NULL, entity VARCHAR(100) NOT NULL, entity_id BIGINT UNSIGNED NULL, before_data JSON NULL, after_data JSON NULL, ip_address VARCHAR(45) NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(actor_id) REFERENCES users(id) ON DELETE SET NULL, INDEX(entity,entity_id,created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS user_notification_reads (
 user_id BIGINT UNSIGNED NOT NULL,
 notice_key CHAR(40) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 read_at DATETIME NOT NULL,
 PRIMARY KEY(user_id,notice_key),
 INDEX(read_at),
 CONSTRAINT fk_notification_reads_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS movement_corrections (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 movement_id BIGINT UNSIGNED NOT NULL UNIQUE,
 correction_no VARCHAR(40) NOT NULL UNIQUE,
 reason TEXT NOT NULL,
 actor_id BIGINT UNSIGNED NOT NULL,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 CONSTRAINT fk_movement_corrections_movement FOREIGN KEY(movement_id) REFERENCES movements(id),
 CONSTRAINT fk_movement_corrections_actor FOREIGN KEY(actor_id) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
