<script setup>
import { useLiveRefresh } from '@/composables/useLiveRefresh';
import Pagination from '@/components/Pagination.vue';
import { statusOptions } from '@/workflowStatus';
import StatusBadge from '@/components/StatusBadge.vue';
import WorkflowStatusGuide from '@/components/WorkflowStatusGuide.vue';
import { computed,onBeforeUnmount,onMounted,reactive,ref,watch } from 'vue';import {useRoute} from 'vue-router';import api from '@/services/api';import{currentUser}from'@/router';import ExportActions from '@/components/ExportActions.vue';import ListFilterBar from '@/components/ListFilterBar.vue';import { formatDisplayDate, isDateValue, todayIsoDate } from '@/dateUtils';
const route=useRoute(),user=ref(currentUser()),result=ref(null),options=ref({suppliers:[],products:[],orders:[]}),busy=ref(false),saving=ref(false),modal=ref(false),confirmOrder=ref(null),error=ref(''),notice=ref(''),search=ref('');let timer,nextReceiptLineKey=0;
const page=computed(()=>route.path.slice(1)),isPurchases=computed(()=>page.value==='purchases'),rows=computed(()=>result.value?.data||[]),form=reactive({supplier_id:'',ordered_on:todayIsoDate(),expected_on:'',note:'',items:[{product_id:'',qty:'',unit_cost:''}]}),receipt=reactive({purchase_order_id:'',received_on:todayIsoDate(),invoice_no:'',contract_no:'',note:'',items:[]}),filters=reactive({status:'',supplier_id:'',from:'',to:''}),can=p=>Boolean(user.value?.permissions?.[p]);
const filterSelects=computed(()=>[...(isPurchases.value?[{key:'status',label:'Կարգավիճակ',allLabel:'Բոլոր կարգավիճակները',options:statusOptions('purchases')}]:[]),{key:'supplier_id',label:'Մատակարար',allLabel:'Բոլոր մատակարարները',options:(result.value?.filter_options?.suppliers||[]).map(supplier=>({value:supplier.id,label:supplier.name}))}]);
const filterDateLabels=computed(()=>isPurchases.value?['Պատվերի օր՝ սկսած','Պատվերի օր՝ մինչև']:['Ստացման օր՝ սկսած','Ստացման օր՝ մինչև']);
let listRequestVersion=0;
let formRequestVersion=0;
const openingForm=ref(false);
async function load(pageNo=1,pageSize=result.value?.pagination.per_page||15){const version=++listRequestVersion;busy.value=true;error.value='';try{const r=await api.get(`pages/${page.value}`,{params:{...filters,page:pageNo,per_page:pageSize,search:search.value||undefined}});if(version===listRequestVersion)result.value=r.data;}catch(e){if(version===listRequestVersion)error.value=e.response?.data?.message||'Ցանկը չհաջողվեց բեռնել։';}finally{if(version===listRequestVersion)busy.value=false;}}
function resetFilters(){Object.assign(filters,{status:'',supplier_id:'',from:'',to:''});load(1);}
const userScope=value=>JSON.stringify([value?.id,value?.location_id??value?.branch?.id,...['purchases.view','purchases.create','purchases.approve','receipts.view','receipts.create'].map(key=>Boolean(value?.permissions?.[key]))]);
const updateUser=(event)=>{const changed=userScope(user.value)!==userScope(event.detail);user.value=event.detail;if(changed){formRequestVersion+=1;listRequestVersion+=1;openingForm.value=false;modal.value=false;confirmOrder.value=null;result.value=null;receipt.items=[];if(can(`${page.value}.view`))load(1);}};
watch(search,()=>{clearTimeout(timer);timer=setTimeout(()=>load(1),250);});onMounted(()=>{load();window.addEventListener('lager:user',updateUser);});
onBeforeUnmount(()=>{listRequestVersion+=1;formRequestVersion+=1;clearTimeout(timer);window.removeEventListener('lager:user',updateUser);});
async function openCreate(orderId=0){
    if(saving.value||!can(`${page.value}.create`))return;
    const kind=page.value,version=++formRequestVersion;
    error.value='';openingForm.value=true;
    try{
        const r=await api.get(`purchasing/${kind}/options`);
        if(version!==formRequestVersion||kind!==page.value||!can(`${kind}.create`))return;
        options.value=r.data.data;
        if(kind==='purchases')Object.assign(form,{supplier_id:'',ordered_on:todayIsoDate(),expected_on:'',note:'',items:[{product_id:'',qty:'',unit_cost:''}]});
        else{
            Object.assign(receipt,{purchase_order_id:'',received_on:todayIsoDate(),invoice_no:'',contract_no:'',note:'',items:[]});
            if(orderId){
                const selectedOrder=options.value.orders.find(item=>Number(item.id)===orderId);
                if(!selectedOrder?.items?.length){notice.value='Այս պատվերը չունի մուտքագրման ենթակա մնացորդ կամ դեռ չի հաստատվել։';return;}
                receipt.purchase_order_id=String(selectedOrder.id);
            }
        }
        modal.value=true;
    }catch(e){if(version===formRequestVersion)error.value=e.response?.data?.message||'Ձևի տվյալները չհաջողվեց բեռնել։';}
    finally{if(version===formRequestVersion)openingForm.value=false;}
}
const canRegisterReceipt=row=>row.status==='approved'&&Number(row.has_remaining_items)===1&&can('receipts.view')&&can('receipts.create');
function addItem(){form.items.push({product_id:'',qty:'',unit_cost:''});}function removeItem(i){if(form.items.length>1)form.items.splice(i,1);}
const order=computed(()=>options.value.orders.find(o=>Number(o.id)===Number(receipt.purchase_order_id))||null);
watch(()=>receipt.purchase_order_id,()=>{receipt.items=(order.value?.items||[]).map(i=>({line_key:++nextReceiptLineKey,purchase_order_item_id:i.id,name:i.name,code:i.code,unit:i.unit,expiry_control:i.expiry_control,ordered_qty:Number(i.ordered_qty),received_qty:Number(i.received_qty),remaining:Number(i.ordered_qty)-Number(i.received_qty),qty:'',lot_no:'',expires_on:'',bin_location:''}));});
watch(()=>route.query.order,value=>{const id=typeof value==='string'&&/^\d+$/.test(value)?Number(value):0;if(!isPurchases.value&&can('receipts.view')&&can('receipts.create')&&Number.isSafeInteger(id)&&id>0)openCreate(id);},{immediate:true});
function addLot(line){const index=receipt.items.indexOf(line);receipt.items.splice(index+1,0,{...line,line_key:++nextReceiptLineKey,is_extra:true,qty:'',lot_no:'',expires_on:'',bin_location:''});}
function removeLot(line){if(!line.is_extra)return;const index=receipt.items.findIndex(item=>item.line_key===line.line_key);if(index>=0)receipt.items.splice(index,1);}
function remainingFor(line){const alreadyEntered=receipt.items.reduce((sum,row)=>row.purchase_order_item_id===line.purchase_order_item_id&&row.line_key!==line.line_key?sum+Number(row.qty||0):sum,0);return Math.max(0,line.remaining-alreadyEntered);}
async function save(){if(saving.value)return;saving.value=true;error.value='';try{if(isPurchases.value){const body={...form,supplier_id:Number(form.supplier_id),items:form.items.map(i=>({...i,product_id:Number(i.product_id),qty:Number(i.qty),unit_cost:Number(i.unit_cost)}))};await api.post('purchases',body);notice.value='Գնման պատվերն ուղարկվեց հաստատման։'}else{const body={...receipt,purchase_order_id:Number(receipt.purchase_order_id),items:receipt.items.filter(i=>Number(i.qty)>0).map(({purchase_order_item_id,qty,lot_no,expires_on,bin_location})=>({purchase_order_item_id,qty:Number(qty),lot_no,expires_on,bin_location}))};await api.post('receipts',body);notice.value='Ապրանքի մուտքը գրանցվեց։'}modal.value=false;await load(1);setTimeout(()=>notice.value='',3200);}catch(e){error.value=Object.values(e.response?.data?.errors||{})[0]?.[0]||e.response?.data?.message||'Տվյալները չպահպանվեցին։';}finally{saving.value=false;}}
async function approve(){if(!confirmOrder.value)return;saving.value=true;error.value='';try{await api.post(`purchases/${confirmOrder.value.id}/approve`);confirmOrder.value=null;notice.value='Գնման պատվերը հաստատվեց։';await load(result.value?.pagination.current_page||1);setTimeout(()=>notice.value='',3200);}catch(e){error.value=e.response?.data?.message||'Պատվերը չհաստատվեց։';}finally{saving.value=false;}}
const displayCell=(key,value)=>value==null||value===''?'—':/(?:_at|_on|_date)$/.test(key)||key==='date'||isDateValue(value)?formatDisplayDate(value):value;
useLiveRefresh(() => load(result.value?.pagination.current_page || 1), { isBusy: () => busy.value || saving.value });
</script>

<template><div class="page-heading"><div><p class="eyebrow">ԳՆՈՒՄ ԵՎ ՄՈՒՏՔԱԳՐՈՒՄ</p><h1>{{route.meta.title}}</h1><p class="muted">{{isPurchases?'Ստեղծեք մատակարարի պատվեր, ապա հաստատեք այն մինչև ապրանքի մուտքագրումը։':'Գրանցեք միայն հաստատված պատվերի փաստացի LOT-երն ու ստացված քանակները։'}}</p></div><button v-if="can(`${page}.create`)" class="primary-button" :disabled="openingForm || saving" @click="openCreate()"><span><AppIcon name="add" /></span>{{isPurchases?'Նոր գնման պատվեր':'Գրանցել մուտք'}}</button></div>
<div v-if="error&&!modal&&!confirmOrder" class="alert-error" role="alert">{{error}}</div><div v-if="notice" class="notice-success" role="status">{{notice}}</div>
<WorkflowStatusGuide v-if="isPurchases" workflow="purchases" />
<section class="table-card"><div class="table-toolbar"><label class="search-input"><span class="search-icon"><AppIcon name="search" /></span><input v-model="search" class="form-control" placeholder="Որոնել ըստ համարի, մատակարարի կամ հաշվի…"></label><div class="list-count">Ընդամենը՝ <b>{{result?.pagination.total??'…'}}</b></div><ExportActions :page="page" :search="search" :filters="filters" :disabled="busy" /></div><ListFilterBar :model-value="filters" @change="filters[$event.key] = $event.value" :selects="filterSelects" :date-range="true" :date-labels="filterDateLabels" @apply="load(1)" @reset="resetFilters" /><div class="table-scroll"><table class="data-table"><thead><tr><th v-for="(label,key) in result?.columns||{}" :key="key">{{label}}</th><th v-if="isPurchases">Գործողություն</th></tr></thead><tbody><tr v-for="row in rows" :key="row.id"><td v-for="(label,key) in result?.columns||{}" :key="key"><StatusBadge v-if="key==='status'&&isPurchases" workflow="purchases" :status="row[key]" /><strong v-else-if="key.endsWith('_no')">{{row[key]}}</strong><span v-else>{{displayCell(key,row[key])}}</span></td><td v-if="isPurchases"><button v-if="row.status==='pending'&&can('purchases.approve')" class="secondary-button compact-action" @click="confirmOrder=row">Հաստատել</button><RouterLink v-else-if="canRegisterReceipt(row)" class="secondary-button compact-action" :to="{path: '/receipts', query: {order: String(row.id)}}">Գրանցել մուտք</RouterLink><span v-else-if="row.status==='approved' && row.has_remaining_items !== undefined && Number(row.has_remaining_items)===0" class="muted">Մուտքագրման մնացորդ չկա</span><span v-else class="muted">—</span></td></tr><tr v-if="!busy&&result&&!rows.length"><td :colspan="Object.keys(result.columns).length+(isPurchases?1:0)" class="table-empty">Գրառումներ դեռ չկան։</td></tr><tr v-if="busy&&!result"><td colspan="8" class="table-empty">Բեռնվում է…</td></tr></tbody></table></div><Pagination v-if="result" :pagination="result.pagination" :busy="busy" @page-change="load" @per-page-change="load(1, $event)" /></section>

<div v-if="modal" class="modal-backdrop" @click.self="modal=false"><form class="modal-card purchase-modal" @submit.prevent="save"><div class="modal-header"><div><p class="eyebrow">{{isPurchases?'ՄԱՏԱԿԱՐԱՐԻ ՊԱՏՎԵՐ':'ԱՊՐԱՆՔԻ ՄՈՒՏՔ'}}</p><h2>{{isPurchases?'Նոր գնման պատվեր':'Գրանցել ապրանքի մուտք'}}</h2><p>{{isPurchases?'Պատվերը կհայտնվի հաստատման հերթում։':'Ընդունվող քանակը չի կարող գերազանցել պատվերի չստացված մնացորդը։'}}</p></div><button class="icon-button close-button" type="button" @click="modal=false"><AppIcon name="xmark" /></button></div>
<template v-if="isPurchases"><div class="form-grid"><label class="form-field">Մատակարար *<select v-searchable-select v-model="form.supplier_id" class="form-control" required><option value="">Ընտրել մատակարարին</option><option v-for="s in options.suppliers" :key="s.id" :value="s.id">{{s.name}}</option></select></label><label class="form-field">Պատվերի ամսաթիվ *<DatePicker v-model="form.ordered_on" :required="true" /></label><label class="form-field">Սպասվող մուտք<DatePicker v-model="form.expected_on" :min="form.ordered_on" /></label><label class="form-field">Նշում<input v-model.trim="form.note" class="form-control"></label></div><div class="transfer-lines"><div class="section-label">Պատվերի ապրանքներ</div><div v-for="(line,i) in form.items" :key="i" class="purchase-line"><label class="form-field">Ապրանք<select v-searchable-select v-model="line.product_id" class="form-control" required><option value="">Ընտրել</option><option v-for="p in options.products" :key="p.id" :value="p.id">{{p.code}} · {{p.name}}</option></select></label><label class="form-field">Քանակ<input v-model="line.qty" class="form-control" type="number" min="0.001" step="0.001" required></label><label class="form-field">Միավորի գին<input v-model="line.unit_cost" class="form-control" type="number" min="0" step="0.01" required></label><button v-if="form.items.length>1" class="icon-button danger remove-line" type="button" @click="removeItem(i)"><AppIcon name="xmark" /></button></div><button class="secondary-button add-line" type="button" @click="addItem"><AppIcon name="add" /> Ավելացնել ապրանք</button></div></template>
<template v-else><div class="form-grid"><label class="form-field span-2">Հաստատված պատվեր *<select v-searchable-select v-model="receipt.purchase_order_id" class="form-control" required><option value="">Ընտրել պատվերը</option><option v-for="o in options.orders" :key="o.id" :value="o.id">{{o.order_no}} · {{o.supplier}}</option></select></label><label class="form-field">Ստացման ամսաթիվ *<DatePicker v-model="receipt.received_on" :required="true" /></label><label class="form-field">Հաշիվ-ապրանքագիր<input v-model.trim="receipt.invoice_no" class="form-control"></label><label class="form-field">Պայմանագիր<input v-model.trim="receipt.contract_no" class="form-control"></label><label class="form-field">Նշում<input v-model.trim="receipt.note" class="form-control"></label></div><div v-if="receipt.items.length" class="receipt-lines"><div class="section-label">Փաստացի ընդունում՝ յուրաքանչյուր LOT-ը լրացրեք առանձին տողով</div><div v-for="line in receipt.items" :key="line.line_key" class="receipt-line"><div class="receipt-lot-product"><b>{{line.code}} · {{line.name}}</b><small class="cell-subtitle">Պատվեր՝ {{line.ordered_qty}} · Մուտքագրված՝ {{line.received_qty}} · Պատվերի մնացորդ՝ {{line.remaining}} {{line.unit}}</small><div class="receipt-lot-actions"><button type="button" class="secondary-button add-line" @click="addLot(line)"><AppIcon name="add" /> Ավելացնել LOT</button><button v-if="line.is_extra" type="button" class="danger-button receipt-remove-lot" :aria-label="`${line.code} ապրանքի ավելացված LOT-ը հեռացնել`" @click="removeLot(line)"><AppIcon name="xmark" /> Հեռացնել LOT-ը</button></div></div><label class="form-field">Քանակ<input v-model="line.qty" class="form-control" type="number" min="0" :max="remainingFor(line)" step="0.001"></label><label class="form-field">LOT համար<input v-model.trim="line.lot_no" class="form-control" :required="Number(line.qty)>0"></label><label class="form-field">Պիտանի է մինչև<DatePicker v-model="line.expires_on" :min="receipt.received_on" :required="Number(line.qty)>0&&line.expiry_control" /></label><label class="form-field">Դարակ<input v-model.trim="line.bin_location" class="form-control"></label></div></div></template>
<p v-if="error" class="form-error">{{error}}</p><div class="modal-actions"><button type="button" class="secondary-button" @click="modal=false">Չեղարկել</button><button class="primary-button" :disabled="saving">{{saving?'Պահպանվում է…':'Պահպանել'}}</button></div></form></div>
<div v-if="confirmOrder" class="modal-backdrop" @click.self="confirmOrder=null"><section class="modal-card confirm-card"><div class="metric-icon blue"><AppIcon name="success" /></div><h2>Հաստատե՞լ գնման պատվերը</h2><p><b>{{confirmOrder.order_no}}</b> · {{confirmOrder.supplier}}</p><p class="muted">Հաստատումից հետո պատվերի հիման վրա կարելի կլինի գրանցել ապրանքի մուտքը։</p><p v-if="error" class="form-error">{{error}}</p><div class="modal-actions"><button class="secondary-button" @click="confirmOrder=null">Չեղարկել</button><button class="primary-button" :disabled="saving" @click="approve">Հաստատել պատվերը</button></div></section></div></template>
