<script setup>
import Pagination from '@/components/Pagination.vue';
import { computed, onBeforeUnmount, onMounted, reactive, ref, watch } from 'vue';
import { RouterLink, useRoute } from 'vue-router';
import api from '@/services/api';
import { currentUser } from '@/router';
import ExportActions from '@/components/ExportActions.vue';
import ListFilterBar from '@/components/ListFilterBar.vue';
import { formatDisplayDate } from '@/dateUtils';

const route = useRoute();
const user = ref(currentUser());
const result = ref(null); const options = ref({ branches: [], products: [] });
const requestSuggestions = ref({}); const suggestionBusy = ref(false);
const busy = ref(false); const saving = ref(false); const search = ref(''); const error = ref(''); const notice = ref('');
const modal = ref(false); const reviewModal = ref(false); const confirmAction = ref(null); const editingId = ref(null); const reviewRequest = ref(null);
const filters = reactive({ status: '', urgency: '', branch_id: '', from: '', to: '' });
const form = reactive({ branch_id: '', urgency: 'normal', reason: '', submit_mode: 'send', items: [{ product_id: '', qty: '', note: '' }] });
let debounce;
let listRequestVersion = 0;
let suggestionRequestVersion = 0;
const rows = computed(() => result.value?.data || []);
const filterSelects = computed(() => [
  { key: 'status', label: 'Կարգավիճակ', allLabel: 'Բոլոր փուլերը', options: Object.entries({ draft: 'Սևագիր', sent: 'Ուղարկված', review: 'Ստուգման փուլում', approved: 'Հաստատված', partially_approved: 'Մասնակի հաստատված', collecting: 'Հավաքագրվում է', ready_to_ship: 'Պատրաստ է առաքման', shipped: 'Ուղարկված է', received: 'Ստացված է', closed: 'Փակված', cancelled: 'Չեղարկված', rejected: 'Մերժված' }).map(([value, label]) => ({ value, label })) },
  { key: 'urgency', label: 'Հրատապություն', options: [{ value: 'normal', label: 'Սովորական' }, { value: 'high', label: 'Բարձր' }, { value: 'urgent', label: 'Շտապ' }] },
  { key: 'branch_id', label: 'Մասնաճյուղ', allLabel: 'Բոլոր մասնաճյուղերը', options: (result.value?.filter_options?.branches || []).map((branch) => ({ value: branch.id, label: branch.name })) },
]);
const can = (permission) => Boolean(user.value?.permissions?.[permission]);
const isAdmin = computed(() => user.value?.role?.name === 'admin');
const location = computed(() => Number(user.value?.location_id || 0));

async function load(page=1,pageSize=result.value?.pagination.per_page||15) { const version=++listRequestVersion;busy.value=true;error.value='';try{const r=await api.get('pages/requests',{params:{...filters,page,per_page:pageSize,search:search.value||undefined}});if(version===listRequestVersion)result.value=r.data;}catch(e){if(version===listRequestVersion)error.value=e.response?.data?.message||'Պահանջագրերի ցանկը չհաջողվեց բեռնել։';}finally{if(version===listRequestVersion)busy.value=false;} }
function resetFilters(){Object.assign(filters,{status:'',urgency:'',branch_id:'',from:'',to:''});load(1);}
watch(search,()=>{clearTimeout(debounce);debounce=setTimeout(()=>load(1),250);});
const updateUser=(event)=>{user.value=event.detail;};
onMounted(()=>{load();window.addEventListener('lager:user',updateUser);});
onBeforeUnmount(()=>{listRequestVersion+=1;suggestionRequestVersion+=1;clearTimeout(debounce);window.removeEventListener('lager:user',updateUser);});
async function loadOptions(){const r=await api.get('catalog/requests/options');options.value=r.data.data;}
async function loadSuggestions(){const version=++suggestionRequestVersion;const branchId=Number(form.branch_id||0);requestSuggestions.value={};suggestionBusy.value=false;if(!branchId)return;suggestionBusy.value=true;try{const r=await api.get('requests/suggestions',{params:{branch_id:branchId}});if(version===suggestionRequestVersion)requestSuggestions.value=r.data.data.items||{};}catch(e){if(version===suggestionRequestVersion)error.value=e.response?.data?.message||'Մնացորդի առաջարկը չհաջողվեց բեռնել։';}finally{if(version===suggestionRequestVersion)suggestionBusy.value=false;}}
function suggestionFor(productId){return requestSuggestions.value[String(productId)]||null;}
function useSuggestion(line){const suggestion=suggestionFor(line.product_id);if(suggestion)line.qty=suggestion.suggested;}
async function create(){editingId.value=null;error.value='';requestSuggestions.value={};try{await loadOptions();Object.assign(form,{branch_id:user.value?.branch?.id||'',urgency:'normal',reason:'',submit_mode:'send',items:[{product_id:'',qty:'',note:''}]});modal.value=true;await loadSuggestions();}catch(e){error.value=e.response?.data?.message||'Տվյալները չհաջողվեց բեռնել։';}}
function addLine(){form.items.push({product_id:'',qty:'',note:''});}function removeLine(i){if(form.items.length>1)form.items.splice(i,1);}
async function edit(row){error.value='';requestSuggestions.value={};try{await loadOptions();const r=await api.get(`requests/${row.id}`);const d=r.data.data;editingId.value=row.id;Object.assign(form,{branch_id:d.branch_id,urgency:d.urgency,reason:d.reason||'',submit_mode:'draft',items:d.items.map(x=>({product_id:x.product_id,qty:x.requested_qty,note:x.note||''}))});modal.value=true;await loadSuggestions();}catch(e){error.value=e.response?.data?.message||'Պահանջագիրը չհաջողվեց բացել։';}}
async function save(mode){if(saving.value)return;saving.value=true;error.value='';try{const body={...form,branch_id:Number(form.branch_id),submit_mode:mode,items:form.items.map(x=>({...x,product_id:Number(x.product_id),qty:Number(x.qty)}))};if(editingId.value)await api.put(`requests/${editingId.value}/draft`,body);else await api.post('requests',body);modal.value=false;notice.value=mode==='draft'?'Սևագիրը պահպանվեց։':'Պահանջագիրն ուղարկվեց ստուգման։';await load(1);setTimeout(()=>notice.value='',3200);}catch(e){error.value=Object.values(e.response?.data?.errors||{})[0]?.[0]||e.response?.data?.message||'Պահանջագիրը չպահպանվեց։';}finally{saving.value=false;}}
function canCancel(row){return ['draft','sent','review'].includes(row.status)&&can('requests.edit')&&(isAdmin.value||(Number(row.branch_id)===Number(user.value?.branch?.id)&&Number(row.requested_by)===Number(user.value?.id)));}
function action(row){if(row.status==='draft'&&can('requests.edit')&&(isAdmin.value||(Number(row.branch_id)===Number(user.value?.branch?.id)&&Number(row.requested_by)===Number(user.value?.id))))return ['edit','Խմբագրել'];if(row.status==='sent'&&can('requests.approve'))return ['start_review','Վերցնել ստուգման'];if(row.status==='review'&&can('requests.approve'))return ['review','Դիտարկել'];if(canCancel(row))return ['cancel','Չեղարկել'];if(['approved','partially_approved'].includes(row.status)&&can('requests.edit')&&(location.value===0||isAdmin.value))return ['collect','Սկսել հավաքագրումը'];if(row.status==='collecting'&&can('requests.edit')&&(location.value===0||isAdmin.value))return ['ready','Պատրաստ է առաքման'];if(row.status==='ready_to_ship'&&can('requests.edit')&&(location.value===0||isAdmin.value))return ['ship','Ուղարկել'];if(row.status==='shipped'&&can('requests.edit')&&(isAdmin.value||Number(row.branch_id)===Number(user.value?.branch?.id)))return ['receive','Հաստատել ստացումը'];if(row.status==='received'&&can('requests.edit')&&(isAdmin.value||Number(row.branch_id)===Number(user.value?.branch?.id)))return ['close','Փակել'];return null;}
async function openReview(row){error.value='';try{const r=await api.get(`requests/${row.id}`);reviewRequest.value=r.data.data;reviewRequest.value.items=reviewRequest.value.items.map(x=>({...x,approve_qty:x.approved_qty||Math.min(Number(x.requested_qty)||0,Number(x.central_free_qty)||0)}));reviewModal.value=true;}catch(e){error.value=e.response?.data?.message||'Պահանջագրի տողերը չհաջողվեց բացել։';}}
async function review(decision){const row=reviewRequest.value;if(!row||saving.value)return;saving.value=true;error.value='';try{const data={decision};if(decision==='approve')data.approved=Object.fromEntries(row.items.map(x=>[x.id,Number(x.approve_qty||0)]));if(decision==='reject')data.rejection_reason=row.rejection_reason||'';await api.post(`requests/${row.id}/review`,data);reviewModal.value=false;notice.value=decision==='reject'?'Պահանջագիրը մերժվեց։':'Պահանջագրի որոշումը պահպանվեց։';await load(result.value?.pagination.current_page||1);setTimeout(()=>notice.value='',3200);}catch(e){error.value=Object.values(e.response?.data?.errors||{})[0]?.[0]||e.response?.data?.message||'Որոշումը չպահպանվեց։';}finally{saving.value=false;}}
function requestAction(row,key){if(key==='edit')return edit(row);if(key==='review')return openReview(row);if(key==='start_review')return reviewFor(row,'start_review');confirmAction.value={row,key};}
async function reviewFor(row,decision){if(saving.value)return;saving.value=true;error.value='';try{await api.post(`requests/${row.id}/review`,{decision});notice.value='Պահանջագիրը տեղափոխվեց ստուգման փուլ։';await load(result.value?.pagination.current_page||1);}catch(e){error.value=e.response?.data?.message||'Գործողությունը չկատարվեց։';}finally{saving.value=false;}}
async function runAction(){if(!confirmAction.value||saving.value)return;saving.value=true;error.value='';const {row,key}=confirmAction.value;try{await api.post(`requests/${row.id}/${key}`);confirmAction.value=null;notice.value='Գործողությունը կատարվեց։';await load(result.value?.pagination.current_page||1);}catch(e){error.value=e.response?.data?.message||'Գործողությունը չկատարվեց։';}finally{saving.value=false;}}
const statusLabel=s=>({draft:'Սևագիր',sent:'Ուղարկված',review:'Ստուգման փուլում',approved:'Հաստատված',partially_approved:'Մասնակի հաստատված',collecting:'Հավաքագրվում է',ready_to_ship:'Պատրաստ է առաքման',shipped:'Ուղարկված է',received:'Ստացված է',closed:'Փակված',cancelled:'Չեղարկված',rejected:'Մերժված'}[s]||s);
const actionTitle=k=>({cancel:'Չեղարկե՞լ պահանջագիրը',collect:'Սկսե՞լ հավաքագրումը',ready:'Նշե՞լ որպես առաքման պատրաստ',ship:'Ուղարկե՞լ մասնաճյուղ',receive:'Հաստատե՞լ ստացումը',close:'Փակե՞լ պահանջագիրը'}[k]||'Հաստատե՞լ գործողությունը');
</script>

<template>
<div class="page-heading"><div><p class="eyebrow">ՊԱՀԱՆՋԻՑ ՄԻՆՉԵՎ ՍՏԱՑՈՒՄ</p><h1>{{route.meta.title}}</h1><p class="muted">Պահանջագիրը անցնում է ստուգման, հաստատման, հավաքագրման, առաքման և ստացման փուլերով։</p></div><button v-if="can('requests.create')" class="primary-button" @click="create"><span><AppIcon name="add" /></span>Նոր պահանջագիր</button></div>
<div v-if="error&&!modal&&!reviewModal&&!confirmAction" class="alert-error" role="alert">{{error}}</div><div v-if="notice" class="notice-success" role="status">{{notice}}</div>
<section class="table-card"><div class="table-toolbar"><label class="search-input"><span class="search-icon"><AppIcon name="search" /></span><input v-model="search" class="form-control" placeholder="Որոնել համարով, մասնաճյուղով կամ կարգավիճակով…"></label><div class="list-count">Ընդամենը՝ <b>{{result?.pagination.total??'…'}}</b></div><ExportActions page="requests" :search="search" :filters="filters" :disabled="busy" /></div><ListFilterBar :model-value="filters" @change="filters[$event.key] = $event.value" :selects="filterSelects" :date-range="true" @apply="load(1)" @reset="resetFilters" />
<div class="table-scroll"><table class="data-table"><thead><tr><th>Պահանջագիր</th><th>Մասնաճյուղ</th><th>Հրատապություն</th><th>Կարգավիճակ</th><th>Ստեղծվել է</th><th>Գործողություն</th></tr></thead><tbody><tr v-for="row in rows" :key="row.id"><td><strong>{{row.request_no}}</strong><RouterLink v-if="['shipped','received','closed'].includes(row.status)" class="dispatch-link" :to="'/requests/' + row.id + '/dispatch'">Դիտել / տպել բաշխումը</RouterLink></td><td>{{row.branch}}</td><td>{{({normal:'Սովորական',high:'Բարձր',urgent:'Շտապ'})[row.urgency]||row.urgency}}</td><td><span class="workflow-status" :class="`state-${row.status}`">{{statusLabel(row.status)}}</span></td><td>{{formatDisplayDate(row.created_at)}}</td><td><button v-if="action(row)" class="secondary-button compact-action" :disabled="saving" @click="requestAction(row,action(row)[0])">{{action(row)[1]}}</button><button v-if="canCancel(row) && action(row)?.[0] !== 'cancel'" class="secondary-button compact-action" :disabled="saving" @click="requestAction(row,'cancel')">Չեղարկել</button><span v-if="!action(row) && !canCancel(row)" class="muted">—</span></td></tr><tr v-if="!busy&&result&&!rows.length"><td colspan="6" class="table-empty">{{search?'Որոնմանը համապատասխան պահանջագիր չկա։':'Պահանջագրեր դեռ չկան։'}}</td></tr><tr v-if="busy&&!result"><td colspan="6" class="table-empty">Բեռնվում է…</td></tr></tbody></table></div>
<Pagination v-if="result" :pagination="result.pagination" :busy="busy" @page-change="load" @per-page-change="load(1, $event)" /></section>

<div v-if="modal" class="modal-backdrop" @click.self="modal=false"><form class="modal-card request-modal" @submit.prevent="save('send')"><div class="modal-header"><div><p class="eyebrow">ՄԱՍՆԱՃՅՈՒՂԱՅԻՆ ՊԱՀԱՆՋ</p><h2>{{editingId?'Խմբագրել սևագիրը':'Նոր պահանջագիր'}}</h2><p>Ավելացրեք ապրանքներն ու քանակները, ապա ուղարկեք կենտրոնական պահեստ։</p></div><button class="icon-button close-button" type="button" @click="modal=false"><AppIcon name="xmark" /></button></div>
<div class="form-grid"><label class="form-field">Մասնաճյուղ *<select v-searchable-select v-model="form.branch_id" class="form-control" :disabled="location>0" required @change="loadSuggestions"><option value="">Ընտրել մասնաճյուղը</option><option v-for="b in options.branches" :key="b.id" :value="b.id">{{b.name}}</option></select></label><label class="form-field">Հրատապություն<select v-searchable-select v-model="form.urgency" class="form-control"><option value="normal">Սովորական</option><option value="high">Բարձր</option><option value="urgent">Շտապ</option></select></label><label class="form-field span-2">Հիմնավորում<textarea v-model.trim="form.reason" class="form-control" placeholder="Պահանջի նպատակը"></textarea></label></div>
<div class="transfer-lines"><div class="section-label">Պահանջվող ապրանքներ</div><div v-for="(line,i) in form.items" :key="i" class="request-line-row"><label class="form-field">Ապրանք<select v-searchable-select v-model="line.product_id" class="form-control" required><option value="">Ընտրել ապրանքը</option><option v-for="p in options.products" :key="p.id" :value="p.id">{{p.code}} · {{p.name}}</option></select><small v-if="suggestionFor(line.product_id)" class="request-stock-hint">Մասնաճյուղում՝ {{suggestionFor(line.product_id).current}} · Միջին ամսական սպառում՝ {{suggestionFor(line.product_id).average}} · Առաջարկ՝ <b>{{suggestionFor(line.product_id).suggested}}</b> <button type="button" class="text-link" @click="useSuggestion(line)">Լրացնել առաջարկը</button></small><small v-else-if="suggestionBusy&&line.product_id" class="request-stock-hint">Մնացորդը հաշվարկվում է…</small></label><label class="form-field">Քանակ<input v-model="line.qty" class="form-control" type="number" min="0.001" step="0.001" required></label><label class="form-field">Նշում<input v-model.trim="line.note" class="form-control"></label><button v-if="form.items.length>1" class="icon-button danger remove-line" type="button" @click="removeLine(i)"><AppIcon name="xmark" /></button></div><button class="secondary-button add-line" type="button" @click="addLine"><AppIcon name="add" /> Ավելացնել ապրանք</button></div>
<p v-if="error" class="form-error">{{error}}</p><div class="modal-actions"><button type="button" class="secondary-button" @click="modal=false">Չեղարկել</button><button type="button" class="secondary-button" :disabled="saving" @click="save('draft')">Պահպանել սևագիր</button><button class="primary-button" :disabled="saving">{{saving?'Պահպանվում է…':'Ուղարկել պահանջագիրը'}}</button></div></form></div>

<div v-if="reviewModal&&reviewRequest" class="modal-backdrop" @click.self="reviewModal=false"><section class="modal-card request-modal"><div class="modal-header"><div><p class="eyebrow">ՊԱՀԱՆՋԱԳՐԻ ԴԻՏԱՐԿՈՒՄ</p><h2>{{reviewRequest.request_no}}</h2><p>{{reviewRequest.branch_name}} · ստուգեք քանակներն ու հաստատման հնարավորությունը։</p></div><button class="icon-button close-button" @click="reviewModal=false"><AppIcon name="xmark" /></button></div><div class="approval-list"><div v-for="line in reviewRequest.items" :key="line.id" class="approval-line"><div><b>{{line.name}}</b><small class="cell-subtitle">Պահանջված՝ {{line.requested_qty}} {{line.unit}} · Մասնաճյուղում՝ {{line.branch_current_qty??'—'}} {{line.unit}} · Միջին ամսական սպառում՝ {{line.branch_monthly_average??'—'}} {{line.unit}} · Կենտրոնի ազատ մնացորդ՝ {{line.central_free_qty??'—'}} {{line.unit}}</small></div><label class="form-field">Հաստատվող<input v-model="line.approve_qty" type="number" min="0" :max="Math.min(Number(line.requested_qty)||0,Number(line.central_free_qty)||0)" step="0.001" class="form-control"></label></div></div><label class="form-field rejection-field">Մերժման պատճառ<textarea v-model.trim="reviewRequest.rejection_reason" class="form-control" placeholder="Պարտադիր է միայն մերժելիս"></textarea></label><p v-if="error" class="form-error">{{error}}</p><div class="modal-actions"><button class="secondary-button" @click="reviewModal=false">Փակել</button><button class="danger-button" :disabled="saving" @click="review('reject')">Մերժել</button><button class="primary-button" :disabled="saving" @click="review('approve')">Հաստատել քանակները</button></div></section></div>

<div v-if="confirmAction" class="modal-backdrop" @click.self="confirmAction=null"><section class="modal-card confirm-card"><div class="metric-icon blue"><AppIcon name="transfers" /></div><h2>{{actionTitle(confirmAction.key)}}</h2><p>Պահանջագիր՝ <b>{{confirmAction.row.request_no}}</b></p><p class="muted">Գործողությունը կպահպանվի պատմությունում և կփոխի պահանջագրի ընթացիկ փուլը։</p><p v-if="error" class="form-error">{{error}}</p><div class="modal-actions"><button class="secondary-button" @click="confirmAction=null">Չեղարկել</button><button class="primary-button" :disabled="saving" @click="runAction">{{saving?'Կատարվում է…':'Հաստատել'}}</button></div></section></div>
</template>
